### ISSUE TITLE
Perfomance is slow because users_who_rated bottleneck

### ISSUE THREAD

**Issue by alrus2797** [white-leaf-devs/recommendation-system#39]
The query to get the users who rated an item (book or movie) takes 3 min or longer if the number of users is 10000, it slows the entire workflow when using item-based distances.

**Comment by quebin31** [comment]
This issue isn't actually solved, we still need to implement this solution to all different controllers. Re-opening.

**Comment by alrus2797** [comment]
Srry, my bad.
Greetings
